# Generated by Django 4.2.4 on 2023-08-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0002_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
