# Generated by Django 4.2.4 on 2023-09-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0006_alter_card_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='serie',
            field=models.CharField(choices=[('rezero', 'Re:Zero'), ('yofukashi', 'Yofukashi No Uta'), ('kimetsu', 'Kimetsu No Yaiba'), ('bocchi', 'Bocchi The Rock!'), ('shingeki', 'Shingeki No Kyojin'), ('boku', 'Boku No Hero'), ('kumo', 'Kumo Desu Ga Nani Ka?'), ('oshi', 'Oshi No Ko'), ('kaguya', 'Kaguya-sama'), ('fullmetal', 'Full Metal Alchemist'), ('pokemon', 'Pokemon')], default='opcion1', max_length=50),
        ),
    ]
