# Generated by Django 4.2.4 on 2023-09-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0009_card_anime_card_manga_card_novela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='card',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='card',
            name='novela',
        ),
        migrations.AddField(
            model_name='card',
            name='formato',
            field=models.CharField(choices=[('Novela', 'Novela'), ('Anime', 'Anime'), ('Manga', 'Manga')], default='Anime', max_length=40),
        ),
    ]
